# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: BrickStore
author: "Robert Griebl"
#email: robert@griebl.org
baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
#github_username: rgriebl

# Build settings

#remote_theme: daattali/beautiful-jekyll@5.0.0
#theme: beautiful-jekyll-theme

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - Gemfile
  - Gemfile.lock
  - .vendor/bundle/
  - .vendor/gem/
  - jekyll.sh

markdown: GFM

#avatar: /assets/images/brickstore.png
#round-avatar: no

title-img: /assets/images/brickstore.png

navbar-var-length: yes
navbar-links:
  '<i class="fas fa-download"></i> Download': "download"
  '<i class="fas fa-bug"></i> Report bugs': "report-bugs"
  '<i class="fas fa-question-circle"></i> Documentation':
    - 'Installation instructions': "installation"
    - 'Tutorials': "tutorials"
    - 'Building from source': "compile"
    - 'Translations': "translations"
  '<i class="fa fa-heart"></i> Support': "support"
  
remove-ads: yes

social-network-links:
  github: rgriebl
  rss: no

url-pretty: "www.brickstore.dev"

edit_page_button: yes
